provider: openai # or anthropic
model: gpt-5-mini
categories: [Quality, Correctness, Security]
publish: false
graph:
  enabled: true
  depth: 2
  maxFiles: 20
  maxSlicesPerFile: 4
  maxCharsPerSlice: 1500
